spring:
  # app이름
  application:
    name: mosi
  #DB연결정보
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##mosi
    password: mosi1234
  #ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      file-size-threshold: 0B
      resolve-lazily: true

# 웹서버 포트
server:
  port: 9090

# 로그레벨
# trace > debug > info > warn > error > fatal
logging:
  level:
    root: info



# 게시판 업로드 위치
upload:
  path: C:\KDT\projects\uploads\bbs
  url-prefix: /static/uploads




naver:
  gateway:       # 지도·지오코딩  ➜ API Gateway(Hmac 서명)
    base-url: https://maps.apigw.ntruss.com
    clientId: ${NAVER_MAPS_CLIENT_ID}
    access-key: ${NAVER_MAPS_CLIENT_ID}
    secret-key: ${NAVER_MAPS_CLIENT_SECRET}
  open:          # 지역·검색  ➜ OpenAPI(Client ID/Secret)
    base-url: https://openapi.naver.com
    client-id: ${NAVER_OPEN_CLIENT_ID}
    client-secret: ${NAVER_OPEN_CLIENT_SECRET}