-- 시퀀스
CREATE SEQUENCE ORDERS_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ORDER_ITEMS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 주문헤더
CREATE TABLE ORDERS (
  ORDER_ID     NUMBER(10)           NOT NULL,
  ORDER_CODE   VARCHAR2(20)         NOT NULL,                  -- MOSI-YYYYMMDD-001
  BUYER_ID     NUMBER(10)           NOT NULL,
  TOTAL_PRICE  NUMBER(10)           NOT NULL,
  ORDER_DATE   TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
  STATUS       VARCHAR2(20)         DEFAULT '결제대기' NOT NULL,
  CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
  CONSTRAINT CK_ORDERS_STATUS CHECK (STATUS IN ('결제대기','결제완료','취소'))
);

ALTER TABLE ORDERS
  ADD CONSTRAINT FK_ORDERS_BUYER
  FOREIGN KEY (BUYER_ID) REFERENCES MEMBER (MEMBER_ID);

-- 주문상세
CREATE TABLE ORDER_ITEMS (
  ORDER_ITEM_ID   NUMBER(10)       NOT NULL,
  ORDER_ID        NUMBER(10)       NOT NULL,
  PRODUCT_ID      NUMBER(10)       NOT NULL,
  SELLER_ID       NUMBER(10)       NOT NULL,
  QUANTITY        NUMBER(5)        DEFAULT 1 NOT NULL,
  ORIGINAL_PRICE  NUMBER(10)       NOT NULL,
  SALE_PRICE      NUMBER(10)       NOT NULL,
  REQUEST         VARCHAR2(150),
  OPTION_TYPE     VARCHAR2(30)     NOT NULL,                   -- '기본코스','가이드포함'
  REVIEWED        CHAR(1)          DEFAULT 'N' NOT NULL,       -- Y/N
  CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ITEM_ID),
  CONSTRAINT FK_OI_ORDER   FOREIGN KEY (ORDER_ID)   REFERENCES ORDERS  (ORDER_ID),
  CONSTRAINT FK_OI_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
  CONSTRAINT FK_OI_SELLER  FOREIGN KEY (SELLER_ID)  REFERENCES MEMBER_ID  (MEMBER_ID),
  CONSTRAINT CK_OI_REVIEWED CHECK (REVIEWED IN ('Y','N')),
  CONSTRAINT CK_OI_OPTION   CHECK (OPTION_TYPE IN ('기본코스','가이드포함'))
);




INSERT INTO ORDERS (ORDER_ID, ORDER_CODE, BUYER_ID, TOTAL_PRICE)
VALUES (ORDERS_SEQ.NEXTVAL, 'MOSI-20250818-001', 5, 55000);

INSERT INTO ORDERS (ORDER_ID, ORDER_CODE, BUYER_ID, TOTAL_PRICE)
VALUES (ORDERS_SEQ.NEXTVAL, 'MOSI-20250818-002', 5, 120000);

INSERT INTO ORDERS (ORDER_ID, ORDER_CODE, BUYER_ID, TOTAL_PRICE)
VALUES (ORDERS_SEQ.NEXTVAL, 'MOSI-20250818-003', 5, 89000);



-- 주문 MOSI-20250818-001 (TOTAL=55,000) → 아이템 1개
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE,request, OPTION_TYPE)
VALUES (
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-001'),
  1,
  6,
  1, 55000, 55000,'안전 여행', '기본코스'
);

-- 주문 MOSI-20250818-002 (TOTAL=120,000) → 아이템 3개
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE, OPTION_TYPE)
VALUES (
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-002'),
  1,
  6,
  1, 40000, 40000, '기본코스'
);

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE, OPTION_TYPE)
VALUES (
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-002'),
  1,
  6,
  2, 20000, 20000, '가이드포함'
);

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE, OPTION_TYPE)
VALUES (
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-002'),
  1,
  6,
  4, 10000, 10000, '기본코스'
);

-- 주문 MOSI-20250818-003 (TOTAL=89,000) → 아이템 2개
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE, OPTION_TYPE)
VALUES (
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-003'),
  1,
  6,
  1, 49000, 49000, '가이드포함'
);

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE, OPTION_TYPE)
VALUES (
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-003'),
  1,
  6,
  2, 20000, 20000, '기본코스'
);




