DROP TABLE REVIEW_REPORT;
DROP TABLE REVIEW_TAG;
DROP TABLE TAG;
DROP TABLE REVIEW;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE TAG_SEQ;


DROP TABLE order_items;
DROP TABLE orders;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE ORDER_ITEMS_SEQ;


-- 시퀀스
CREATE SEQUENCE ORDERS_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ORDER_ITEMS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 주문헤더
CREATE TABLE ORDERS (
  ORDER_ID     NUMBER(10)           NOT NULL,
  ORDER_CODE   VARCHAR2(20)         NOT NULL,                  -- MOSI-YYYYMMDD-001
  BUYER_ID     NUMBER(10)           NOT NULL,
  TOTAL_PRICE  NUMBER(10)           NOT NULL,
  ORDER_DATE   TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,
  STATUS       VARCHAR2(20)         DEFAULT '결제대기' NOT NULL,
  CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
  CONSTRAINT CK_ORDERS_STATUS CHECK (STATUS IN ('결제대기','결제완료','취소'))
);

ALTER TABLE ORDERS
  ADD CONSTRAINT FK_ORDERS_BUYER
  FOREIGN KEY (BUYER_ID) REFERENCES MEMBER (MEMBER_ID);

-- 주문상세
CREATE TABLE ORDER_ITEMS (
  ORDER_ITEM_ID   NUMBER(10)       NOT NULL,
  ORDER_ID        NUMBER(10)       NOT NULL,
  PRODUCT_ID      NUMBER(10)       NOT NULL,
  SELLER_ID       NUMBER(10)       NOT NULL,
  QUANTITY        NUMBER(5)        DEFAULT 1 NOT NULL,
  ORIGINAL_PRICE  NUMBER(10)       NOT NULL,
  SALE_PRICE      NUMBER(10)       NOT NULL,
  REQUEST         VARCHAR2(150),
  OPTION_TYPE     VARCHAR2(30)     NOT NULL,                   -- '기본코스','가이드포함'
  REVIEWED        CHAR(1)          DEFAULT 'N' NOT NULL,       -- Y/N
  CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ITEM_ID),
  CONSTRAINT FK_OI_ORDER   FOREIGN KEY (ORDER_ID)   REFERENCES ORDERS  (ORDER_ID),
  CONSTRAINT FK_OI_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
  CONSTRAINT FK_OI_SELLER  FOREIGN KEY (SELLER_ID)  REFERENCES MEMBER  (MEMBER_ID),
  CONSTRAINT CK_OI_REVIEWED CHECK (REVIEWED IN ('Y','N')),
  CONSTRAINT CK_OI_OPTION   CHECK (OPTION_TYPE IN ('기본코스','가이드포함'))
);




INSERT INTO ORDERS (ORDER_ID, ORDER_CODE, BUYER_ID, TOTAL_PRICE)
VALUES (ORDERS_SEQ.NEXTVAL, 'MOSI-20250818-001', 5, 55000);

INSERT INTO ORDERS (ORDER_ID, ORDER_CODE, BUYER_ID, TOTAL_PRICE)
VALUES (ORDERS_SEQ.NEXTVAL, 'MOSI-20250818-002', 5, 120000);

INSERT INTO ORDERS (ORDER_ID, ORDER_CODE, BUYER_ID, TOTAL_PRICE)
VALUES (ORDERS_SEQ.NEXTVAL, 'MOSI-20250818-003', 5, 89000);



-- 주문 MOSI-20250818-001 (TOTAL=55,000) → 아이템 1개
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE,request, OPTION_TYPE)
VALUES (
  ORDER_ITEMS_SEQ.NEXTVAL,
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-001'),
  1,
  6,
  1, 55000, 55000,'안전 여행', '기본코스'
);

-- 주문 MOSI-20250818-002 (TOTAL=120,000) → 아이템 3개
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE,request,  OPTION_TYPE)
VALUES (
  ORDER_ITEMS_SEQ.NEXTVAL,
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-002'),
  1,
 6,
  1, 40000, 40000,'스릴 만점', '기본코스'
);

INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE,request,  OPTION_TYPE)
VALUES (
  ORDER_ITEMS_SEQ.NEXTVAL,
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-002'),
  1,
  6,
  2, 20000, 20000,'미슐랭', '가이드포함'
);

INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE,request,  OPTION_TYPE)
VALUES (
  ORDER_ITEMS_SEQ.NEXTVAL,
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-002'),
  1,
  6,
  4, 10000, 10000,'놀이공원', '기본코스'
);

-- 주문 MOSI-20250818-003 (TOTAL=89,000) → 아이템 2개
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE,request,  OPTION_TYPE)
VALUES (
  ORDER_ITEMS_SEQ.NEXTVAL,
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-003'),
  1,
  6,
  1, 49000, 49000,'대리만족', '가이드포함'
);

INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID, PRODUCT_ID, SELLER_ID, QUANTITY, ORIGINAL_PRICE, SALE_PRICE,request,  OPTION_TYPE)
VALUES (
  ORDER_ITEMS_SEQ.NEXTVAL,
  (SELECT ORDER_ID FROM ORDERS WHERE ORDER_CODE='MOSI-20250818-003'),
  1,
  6,
  2, 20000, 20000,'분위기', '기본코스'
);
---------------------------------------------------------------------------------------------------------------


-- 시퀀스
CREATE SEQUENCE REVIEW_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TAG_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 주문헤더
CREATE TABLE REVIEW (
  REVIEW_ID     NUMBER(10)           NOT NULL,
  PRODUCT_ID     NUMBER(10)           NOT NULL,
  BUYER_ID     NUMBER(10)           NOT NULL,
  ORDER_item_ID     NUMBER(10)           NOT NULL,
  CONTENT			 clob,
  SCORE        NUMBER(2,1)          NOT NULL,
  SELLER_RECOYN char(1)             DEFAULT 'N',
  STATUS       VARCHAR2(11)         DEFAULT 'R0201',
  CREATE_DATE  timestamp            default systimestamp,
  UPDATE_DATE  timestamp,
  CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_ID),
  CONSTRAINT CK_REVIEW_SCORE CHECK (SCORE BETWEEN 1 AND 5),
  CONSTRAINT CK_REVIEW_seller CHECK (SELLER_RECOYN IN ('Y','N'))
);

ALTER TABLE REVIEW
  ADD CONSTRAINT FK_REVIEW_product
  FOREIGN KEY (PRODUCT_ID) REFERENCES product (PRODUCT_ID);

ALTER TABLE REVIEW
  ADD CONSTRAINT FK_REVIEW_BUYER
  FOREIGN KEY (BUYER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE REVIEW
  ADD CONSTRAINT FK_REVIEW_ORDER
  FOREIGN KEY (ORDER_item_ID) REFERENCES ORDER_items (ORDER_item_ID);


/* ---- TAG (리뷰에 사용할 태그) ---------------------------- */
CREATE TABLE TAG (
  TAG_ID       NUMBER(10)                  NOT NULL,
  LABEL        VARCHAR2(50),
  SLUG         VARCHAR2(50),
  TCATEGORY    VARCHAR2(11),
  COMMONYN     CHAR(1),
  USEYN        CHAR(1)        DEFAULT 'Y'  NOT NULL,              -- 'Y'/'N'
  RECOYN       CHAR(1)        DEFAULT 'N'  NOT NULL,              -- 'Y'/'N'
  CREATE_DATE  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATE_DATE  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TAG                 PRIMARY KEY (TAG_ID),
  CONSTRAINT FK_TAG_TCATEGORY       FOREIGN KEY (TCATEGORY) REFERENCES CODE (CODE_ID) ON DELETE CASCADE,
  CONSTRAINT CK_TAG_COMMONYN        CHECK (COMMONYN IN ('Y','N')),
  CONSTRAINT CK_TAG_USEYN           CHECK (USEYN    IN ('Y','N')),
  CONSTRAINT CK_TAG_RECOYN          CHECK (RECOYN   IN ('Y','N'))
);

/* ---- REVIEW_TAG (리뷰 작성시 선택한 태그) ---------------- */
CREATE TABLE REVIEW_TAG (
  REVIEW_ID    NUMBER(10)  NOT NULL,
  TAG_ID       NUMBER(10)  NOT NULL,
  SORT_ORDER   NUMBER(2),
  CONSTRAINT PK_REVIEW_TAG            PRIMARY KEY (REVIEW_ID, TAG_ID),
  CONSTRAINT FK_REVIEW_TAG_REVIEW     FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW (REVIEW_ID) ON DELETE CASCADE,
  CONSTRAINT FK_REVIEW_TAG_TAG        FOREIGN KEY (TAG_ID)    REFERENCES TAG    (TAG_ID)    ON DELETE CASCADE
);

/* ---- REVIEW_REPORT (리뷰 신고) --------------------------- */
CREATE TABLE REVIEW_REPORT (
  REVIEW_ID    NUMBER(10)  NOT NULL,
  MEMBER_ID    NUMBER(10)  NOT NULL,
  REASON       VARCHAR2(300),
  REPORT_DATE  TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_REVIEW_REPORT         PRIMARY KEY (REVIEW_ID, MEMBER_ID),
  CONSTRAINT FK_REVIEW_REPORT_REVIEW  FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW (REVIEW_ID) ON DELETE CASCADE,
  CONSTRAINT FK_REVIEW_REPORT_MEMBER  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);



/* ===================== B0101 지역 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
VALUES (TAG_SEQ.NEXTVAL, '역세권',           'near-subway',        'B0101', 'N', 'Y', 'N');
INSERT INTO TAG  (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
VALUES (TAG_SEQ.NEXTVAL, '바다 근처',        'seaside-area',       'B0101', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '산 근처',          'mountain-area',      'B0101', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '시장 인접',        'market-area',        'B0101', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '공원 인접',        'park-adjacent',      'B0101', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '도심',            'downtown',           'B0101', 'N', 'Y', 'N');

/* ===================== B0102 반려동물 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '강아지 출입 가능', 'pet-dogs-allowed',   'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '고양이 출입 가능', 'pet-cats-allowed',   'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '대형견 가능',      'large-dogs-ok',      'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '반려동물 전용 좌석','pet-seating',       'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '반려동물 동반 숙박','pet-friendly-stay', 'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '펫키트 제공',      'pet-kit-provided',   'B0102', 'N', 'Y', 'N');

/* ===================== B0103 맛집 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '매운맛',          'spicy',              'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '고기 맛집',        'meat-restaurant',    'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '해산물',          'seafood',            'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '디저트 좋음',      'dessert-good',       'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '가성비 좋음',      'value-for-money',    'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '예약 필수',        'reservation-required','B0103','N', 'Y', 'N');

/* ===================== B0104 문화/역사 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '전시/갤러리',      'exhibition',         'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '박물관',          'museum',             'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '사적지',          'heritage-site',      'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '전통시장',        'traditional-market', 'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '해설 투어',        'guided-tour',        'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '야간 개장',        'night-opening',      'B0104', 'N', 'Y', 'N');

/* ===================== B0105 계절/자연 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '벚꽃 명소',       'cherry-blossom',     'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '단풍 명소',       'autumn-foliage',     'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '해변',            'beach',              'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '산책로',          'walking-trail',      'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '야경 명소',       'night-view',         'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '피크닉 스폿',     'picnic-spot',        'B0105', 'N', 'Y', 'N');

/* ===================== B0106 실버/교통약자 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '휠체어 접근 가능', 'wheelchair-accessible','B0106','N','Y','N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '장애인 화장실',    'accessible-restroom','B0106', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '점자 안내',        'braille-guide',      'B0106', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '엘리베이터',      'elevator',           'B0106', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '경사로',          'ramp',               'B0106', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '저상버스 접근',    'low-floor-bus',      'B0106', 'N', 'Y', 'N');

/* ===================== 공용(공통) 태그 — TCATEGORY='B01' ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '야간 영업',        'open-late',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '가족 친화적',      'family-friendly',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '조용한 분위기',    'quiet-atmosphere',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '포토 스폿',        'photo-spot',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '현금만 가능',      'cash-only',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '주차 가능',        'parking-available',null,  'Y', 'Y', 'N');




